Fixing postinst script

diff --git a/package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/postinst b/package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/postinst
--- a/package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/postinst
+++ b/package/pi-control-panel_VERSION_ARCHITECTURE/DEBIAN/postinst
@@ -89,32 +89,32 @@ case "$1" in
         # End of Enabling supported workers
         
         # Configuring port
-        echo -e '\nConfiguring port for the application...'
+        echo -e 'Configuring port for the application...'
         port=8079
+		socketStats=$(ss -tunlp)
         while [ $port -lt 10000 ]; do
             port=$(($port + 1))
-        #    result=$(sudo ss -tunlp | grep ':'"$port"' ')
-        #    if [ "$result" == "" ]; then
-        #        sed --in-place "/    \"Http\": {/!b;n;c        \"Url\": \"http://+:"$port"\"" /opt/picontrolpanel/Configuration/app$
-        #        break
-        #    fi
+            portInUseResult=$(echo "$socketStats" | grep ':'"$port"' ')
+            if [ "$portInUseResult" == "" ]; then
+                sed --in-place "/    \"Http\": {/!b;n;c        \"Url\": \"http://+:"$port"\"" /opt/picontrolpanel/Configuration/appsettings.json
+                break
+            fi
         done
         
-        #if [ $port -eq 10000 ]; then
-        #    echo -e '\033[0;31mCould not find an available port to run the application\033[0m\n'
-        #    exit 1
-        #fi
+        if [ $port -eq 10000 ]; then
+            echo -e '\033[0;31mCould not find an available port to run the application\033[0m\n'
+            exit 1
+        fi
         # End of Configuring port
         
         chmod +x /opt/picontrolpanel/PiControlPanel.Api.GraphQL
         systemctl enable picontrolpanel
         systemctl start picontrolpanel
         
-        echo -e '\033[0;32mThe installation of PiControlPanel is complete!\033[0m'
+        echo -e '\n\033[0;32mThe installation of PiControlPanel is complete!\033[0m'
         
         raspberryPiIp=$(hostname -I | cut -d' ' -f1)
-		echo -e 'Login @ \033[0;36mhttp://localhost:8080\033[0m from Raspberry Pi or \033[0;36mhttp://'"$raspberryPiIp"':8080\033[0m from another machine\n'
-        #echo -e 'Login @ \033[0;36mhttp://localhost:'"$port"'\033[0m from Raspberry Pi or \033[0;36mhttp://'"$raspberryPiIp"':'"$port"'\033[0m from another machine\n'
+		echo -e 'Login @ \033[0;36mhttp://localhost:'"$port"'\033[0m from Raspberry Pi or \033[0;36mhttp://'"$raspberryPiIp"':'"$port"'\033[0m from another machine\n'
         
     ;;
 
